env:
  browser: true
  es2021: true
extends:
  - 'airbnb-base'
  - 'plugin:react/recommended'
  - 'prettier'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  'no-underscore-dangle': 0
  'no-console': 0
  'object-curly-newline': 0
