env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  import/extensions: 0
  no-underscore-dangle: 0
  no-console: 0
