name: Linter CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node CI check, setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Npm install, build
        run: |
          npm install
        env:
          CI: true
      - name: Run linter
        run: |
          npx eslint .
